#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : libzip
Version  : 1.10.0
Release  : 22
URL      : https://libzip.org/download/libzip-1.10.0.tar.xz
Source0  : https://libzip.org/download/libzip-1.10.0.tar.xz
Summary  : library for handling zip archives
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libzip-bin = %{version}-%{release}
Requires: libzip-lib = %{version}-%{release}
Requires: libzip-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : bzip2-dev
BuildRequires : gnutls-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(libzstd)
BuildRequires : pkgconfig(nettle)
BuildRequires : xz-dev
BuildRequires : zlib-dev
BuildRequires : zstd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: export.patch

%description
This is libzip, a C library for reading, creating, and modifying
zip and zip64 archives. Files can be added from data buffers, files,
or compressed data copied directly from other zip archives. Changes
made without closing the archive can be reverted. Decryption and
encryption of Winzip AES and legacy PKware encrypted files is
supported.

%package bin
Summary: bin components for the libzip package.
Group: Binaries
Requires: libzip-license = %{version}-%{release}

%description bin
bin components for the libzip package.


%package dev
Summary: dev components for the libzip package.
Group: Development
Requires: libzip-lib = %{version}-%{release}
Requires: libzip-bin = %{version}-%{release}
Provides: libzip-devel = %{version}-%{release}
Requires: libzip = %{version}-%{release}

%description dev
dev components for the libzip package.


%package doc
Summary: doc components for the libzip package.
Group: Documentation

%description doc
doc components for the libzip package.


%package lib
Summary: lib components for the libzip package.
Group: Libraries
Requires: libzip-license = %{version}-%{release}

%description lib
lib components for the libzip package.


%package license
Summary: license components for the libzip package.
Group: Default

%description license
license components for the libzip package.


%prep
%setup -q -n libzip-1.10.0
cd %{_builddir}/libzip-1.10.0
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1687544387
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export FCFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export FFLAGS="$FFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -O3 -Wl,-z,x86-64-v3 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd -march=x86-64-v3 "
export CFLAGS="$CFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -march=x86-64-v3 -m64 -Wl,-z,x86-64-v3"
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1687544387
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libzip
cp %{_builddir}/libzip-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/libzip/cacfcacf93466610f196733d660beace4a91f80e || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/zipcmp
/V3/usr/bin/zipmerge
/V3/usr/bin/ziptool
/usr/bin/zipcmp
/usr/bin/zipmerge
/usr/bin/ziptool

%files dev
%defattr(-,root,root,-)
/usr/include/zip.h
/usr/include/zipconf.h
/usr/lib64/cmake/libzip/libzip-config-version.cmake
/usr/lib64/cmake/libzip/libzip-config.cmake
/usr/lib64/cmake/libzip/libzip-targets-relwithdebinfo.cmake
/usr/lib64/cmake/libzip/libzip-targets.cmake
/usr/lib64/cmake/libzip/modules/FindMbedTLS.cmake
/usr/lib64/cmake/libzip/modules/FindNettle.cmake
/usr/lib64/cmake/libzip/modules/Findzstd.cmake
/usr/lib64/libzip.so
/usr/lib64/pkgconfig/libzip.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/libzip/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libzip.so.5.5
/usr/lib64/libzip.so.5
/usr/lib64/libzip.so.5.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libzip/cacfcacf93466610f196733d660beace4a91f80e
