#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libzip
Version  : 1.9.2
Release  : 20
URL      : https://libzip.org/download/libzip-1.9.2.tar.xz
Source0  : https://libzip.org/download/libzip-1.9.2.tar.xz
Summary  : library for handling zip archives
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libzip-bin = %{version}-%{release}
Requires: libzip-lib = %{version}-%{release}
Requires: libzip-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : bzip2-dev
BuildRequires : gnutls-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(nettle)
BuildRequires : xz-dev
BuildRequires : zlib-dev
BuildRequires : zstd-dev
Patch1: export.patch

%description
This is libzip, a C library for reading, creating, and modifying
zip and zip64 archives. Files can be added from data buffers, files,
or compressed data copied directly from other zip archives. Changes
made without closing the archive can be reverted. Decryption and
encryption of Winzip AES and legacy PKware encrypted files is
supported. The API is documented by man pages.

%package bin
Summary: bin components for the libzip package.
Group: Binaries
Requires: libzip-license = %{version}-%{release}

%description bin
bin components for the libzip package.


%package dev
Summary: dev components for the libzip package.
Group: Development
Requires: libzip-lib = %{version}-%{release}
Requires: libzip-bin = %{version}-%{release}
Provides: libzip-devel = %{version}-%{release}
Requires: libzip = %{version}-%{release}

%description dev
dev components for the libzip package.


%package doc
Summary: doc components for the libzip package.
Group: Documentation

%description doc
doc components for the libzip package.


%package lib
Summary: lib components for the libzip package.
Group: Libraries
Requires: libzip-license = %{version}-%{release}

%description lib
lib components for the libzip package.


%package license
Summary: license components for the libzip package.
Group: Default

%description license
license components for the libzip package.


%prep
%setup -q -n libzip-1.9.2
cd %{_builddir}/libzip-1.9.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656448855
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1656448855
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libzip
cp %{_builddir}/libzip-1.9.2/LICENSE %{buildroot}/usr/share/package-licenses/libzip/cacfcacf93466610f196733d660beace4a91f80e
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/zipcmp
/usr/bin/zipmerge
/usr/bin/ziptool

%files dev
%defattr(-,root,root,-)
/usr/include/zip.h
/usr/include/zipconf.h
/usr/lib64/cmake/libzip/libzip-config-version.cmake
/usr/lib64/cmake/libzip/libzip-config.cmake
/usr/lib64/cmake/libzip/libzip-targets-relwithdebinfo.cmake
/usr/lib64/cmake/libzip/libzip-targets.cmake
/usr/lib64/libzip.so
/usr/lib64/pkgconfig/libzip.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libzip/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libzip.so.5
/usr/lib64/libzip.so.5.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libzip/cacfcacf93466610f196733d660beace4a91f80e
